python for machine learning and datascience| oportunity to work on some of the intesresting problems of the world|data science libraries of python scientific computing library numpy working wth data arrays| data analysis library pandas - read/manipulate data from multiple sources

Numpy- scientific computing library, data arrays

each pixel value- grey intensity  by  that value(number).python stores and reads images using arrays of numbers. 
lists as image gets bigger lists occupy lots of memory and operations are slowed down on it. Numpy helps by creating multidimensional array objects
first data analysis library numpy, it is a linear algebra library for python it is imortant for data science because almmost all
of the libraries in pydata ecosystem rely on numpy as one of the main building blocks
numpy is incredibly fast has bindings to c libraies, its c with python wrapper basically
using anaconda helps install all underlying dependencies foe exmalple other linear algebra libraries sync up wit use of conda install
conda install numpy or pip install numpy(if not naconda distribution)
if u have anaconda as ur python dist, and u installed ython using anaconda u install numy by conda install numpy directly into terminal r cmd
numpy arrays- 2 flavours- vectors and matrices
vectors are strictly 1d and matrices are 2d . however matrices can still have only  1 row or 1 column


In [1]:
image= [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]

In [2]:
print image #list of lists can be used like a 3*5 pixel image to repreent image in python

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]


In [5]:
import numpy
n= numpy.arange(10) # 1 dimensional array
print n
type(n) # like a plain python list but not exactly that


[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [8]:
n.reshape(2,5) # 2 dimensional array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
p= numpy.arange(27)
print (p.reshape(3,9)) #2 dimensional array vertical and horizontal

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]


In [11]:
x= numpy.arange(27)

In [12]:
print(x.reshape(3,3,3)) #3 dimensional array, numpy helps us do efficient operations such as iteration between array items and so 
on.
lists and numpy arrays look similar but on low 
level structures are different. 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [16]:
o= [[1,2,3],[4,5,6],[7]]
l= numpy.asarray(o)
print o

[[1, 2, 3], [4, 5, 6], [7]]


In [17]:
type(o)

list

In [18]:
type(l)

numpy.ndarray

#pandas add cool features to numpy arrays- tale headers and indexes not ossible on numpy arrays
#numpy is a low level library simple, low level of storing objects and doing operations
import cv2
image= cv2.imread('path to the image', 0 or 1) 0 grey scale 1- bgr
if u print this image it will give u an array of pixels of the image howmnay ever n dimensional array
to convvert numpy array into image
cv2.imwrite(' create name for the image', givve the array as argument example image)-- o/p is true or False true means file 
created
# slicing interating and indexing of numpy arrays, learn how to access the alues of the numpy array





In [19]:
arr= numpy.arange(10)

In [23]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
type(arr)

numpy.ndarray

In [41]:
arr.shape

(10L,)

In [29]:
arr[1:3]

array([1, 2])

In [36]:
arr.shape

(10L,)

In [42]:
#iterating thru the numpy array
for i in arr:
    print i

0
1
2
3
4
5
6
7
8
9


In [43]:
for i in o: # in each iteration it gets a row and it prints it out, if u want to iterare thru columns transpose and apply for loop
    # if u want value by value for i in image.flat: print i 
    print i

[1, 2, 3]
[4, 5, 6]
[7]


#stacking- concatenating numpy arrays to each other - and splitting- numpy array to smaller arrays
newimage= numpy.hstack((image, image)) # horizontal stacking of same image and putting it in newimage
newimage= numpy.vstack((image, image, image)) # vertical stack
cannot concatenate arrays of different dimensions
new= numpy.hsplit(image,2) 2 should be feasible splits
new= numpy.vsplit(image,3) 3 should be feasible split
type(new) object here is python list of numpy arrays



jose portilla course on numpy
numpy arrays are main way we are going to use numpy library
vectors and matrices both called arrays
my_list=[1,2,3,4,5]
import numpy
n= numpy.array(my_list) # casting the list as an array
print n arraynamed n  as container for that list object
number of brackets can be seen to understand dimensions of the array


In [44]:
n= numpy.arange(27)
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [46]:
#use numpy built in array generation methods for faster and simpler operation
numpy.arange(0,26,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [48]:
# secific types of arrays
# arrays of all zeroes

In [51]:
numpy.zeros(3) # ones nd zeros are functions in numpy that help us with specific array generation # 1d vector

array([ 0.,  0.,  0.])

In [52]:
numpy.zeros((2,5)) #2d vector

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [53]:
numpy.ones(3)

array([ 1.,  1.,  1.])

In [54]:
numpy.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [56]:
guh= numpy.linspace(1,20,50) # want to genratae 50 equidistant points between 1 and 20 including20,equally spaced numbers over an interval 

In [57]:
print guh

[  1.           1.3877551    1.7755102    2.16326531   2.55102041
   2.93877551   3.32653061   3.71428571   4.10204082   4.48979592
   4.87755102   5.26530612   5.65306122   6.04081633   6.42857143
   6.81632653   7.20408163   7.59183673   7.97959184   8.36734694
   8.75510204   9.14285714   9.53061224   9.91836735  10.30612245
  10.69387755  11.08163265  11.46938776  11.85714286  12.24489796
  12.63265306  13.02040816  13.40816327  13.79591837  14.18367347
  14.57142857  14.95918367  15.34693878  15.73469388  16.12244898
  16.51020408  16.89795918  17.28571429  17.67346939  18.06122449
  18.44897959  18.83673469  19.2244898   19.6122449   20.        ]


In [58]:
# identity matrix is useful in linear algebra problems
k= numpy.eye(5) #2 d square matrix rows = column= 5 in this case whose diagonal is 1 and everything else is 0
print k

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [60]:
#arrays of random number generation 
numpy.random.rand(3) # 1d array ( of the given shape u pass in ) populated from with random samples from a uniform distibution 
# over 0 to 1
numpy.random.rand(4,5)# 2d array

array([[ 0.05561212,  0.7348667 ,  0.07528154,  0.68449831,  0.10136973],
       [ 0.29823266,  0.74496394,  0.47329045,  0.65000611,  0.69419318],
       [ 0.12872163,  0.23232154,  0.06270042,  0.85238188,  0.71436309],
       [ 0.13232747,  0.89619776,  0.26700655,  0.8348071 ,  0.69231475]])

In [61]:
numpy.random.rand(3)

array([ 0.95160388,  0.86238311,  0.14522425])

In [62]:
numpy.random.rand(2,2,2) # not as a tuple but just 2,2,2 as argument

array([[[ 0.75471876,  0.26831431],
        [ 0.38379915,  0.02919171]],

       [[ 0.54968595,  0.78074798],
        [ 0.7883123 ,  0.39747456]]])

In [63]:
#generate or return a sample or many samples from std norml dist or gaussian dist we use randn
numpy.random.randn(5) # not from uniform dist from 0 to 1 but from std normal dist centered around 0, 5 random numbers from std normal dist
# when we plot this we can see a normal dist curve


array([-1.32236614, -1.78653595, -1.63277845, -2.09619447,  0.86518147])

In [64]:
numpy.random.randn(5,5) # no tuple, pass in each dimension as a separate argument

array([[ 1.67203547,  0.89480757, -0.91749594,  0.64352901, -1.03743801],
       [-0.29937147,  0.409996  ,  1.64992657,  1.1919827 ,  1.17216701],
       [-0.83596348, -0.30860145,  2.00194554,  0.54192983, -0.02620456],
       [ 1.28881514, -1.15668494,  0.03423525, -2.38364245,  0.34345273],
       [-1.04042971,  0.20066864, -1.59293008, -0.77282994,  1.13215478]])

In [69]:
# final random method randint, returns random integres from a low to high number
numpy.random.randint(1,7,3) # between 1 to 7 and 3 is the size u want, uper bound exclusive

array([6, 1, 6])

In [70]:
# few useful attributes and methods of an array
ama= numpy.arange(25)
ranama= numpy.random.randint(1,20,25)
ama.reshape(5,5) # number of rows into columns = actual numbe of items in the 1d array- like 5*5= 25

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
ranama

array([13, 17,  9, 11, 16, 18, 14, 19, 17,  7,  2,  8, 10,  3, 15, 13,  5,
        1,  9, 12, 16,  6, 18,  7,  9])

In [74]:
#max(ranama) 
ranama.max() # both work

19

In [73]:
min(ranama)

1

In [75]:
ranama.argmax()# returns the index of max

7

In [76]:
ranama.argmin() # retuens index of the min

17

In [82]:
guh.shape # 1d vector of 50 elements

(50L,)

In [86]:
guhu=guh.reshape(10,5)

In [87]:
print guhu

[[  1.           1.3877551    1.7755102    2.16326531   2.55102041]
 [  2.93877551   3.32653061   3.71428571   4.10204082   4.48979592]
 [  4.87755102   5.26530612   5.65306122   6.04081633   6.42857143]
 [  6.81632653   7.20408163   7.59183673   7.97959184   8.36734694]
 [  8.75510204   9.14285714   9.53061224   9.91836735  10.30612245]
 [ 10.69387755  11.08163265  11.46938776  11.85714286  12.24489796]
 [ 12.63265306  13.02040816  13.40816327  13.79591837  14.18367347]
 [ 14.57142857  14.95918367  15.34693878  15.73469388  16.12244898]
 [ 16.51020408  16.89795918  17.28571429  17.67346939  18.06122449]
 [ 18.44897959  18.83673469  19.2244898   19.6122449   20.        ]]


In [88]:
guhu.shape

(10L, 5L)

In [90]:
guhu.dtype # what datatype u have in array , 64 bit float in this case

dtype('float64')

In [91]:
from numpy.random import randint # in case u want to avoid llong senetcnce eveytime
randint(6,7)

6

 indexing and selection and operations on numpy arrays
indexing and selection , select elements or groups of elements from numpy array, use brackets and slice notation


In [92]:
pooja= numpy.arange(0,11)

In [93]:
print pooja

[ 0  1  2  3  4  5  6  7  8  9 10]


In [94]:
pooja[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
pooja[1:5]

array([1, 2, 3, 4])

In [99]:
pooja[8]

8

In [101]:
pooja[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
pooja[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [103]:
pooja[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
poo= numpy.arange(44,55)

In [105]:
poo

array([44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54])

In [106]:
poo[5:]

array([49, 50, 51, 52, 53, 54])

In [107]:
poo[:7] # works similarly for a python list, but differ from a list because of their broadcast ability

array([44, 45, 46, 47, 48, 49, 50])

In [108]:
poo[0:4]=666 #broadcasting value 666 from index 0 to 3 excluding 4

In [109]:
poo

array([666, 666, 666, 666,  48,  49,  50,  51,  52,  53,  54])

In [112]:
red= numpy.arange(25,36)

In [113]:
red

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [114]:
slice_red= red[4:9] # this is not creating another array this is just a separate view of those elements form index 4 to 8
slice_red

array([29, 30, 31, 32, 33])

In [115]:
slice_red[:]=666

In [116]:
slice_red

array([666, 666, 666, 666, 666])

In [117]:
red # so changing the view changed the original array :) numpy does this beacuse memory issues can occur with mutliple 
#huge arrays, to avoid this it can actually avoid creating copies and instead create views


array([ 25,  26,  27,  28, 666, 666, 666, 666, 666,  34,  35])

In [118]:
# create copy and not reference original array further, use copy
red_copy= red.copy()

In [119]:
print red
print red_copy

[ 25  26  27  28 666 666 666 666 666  34  35]
[ 25  26  27  28 666 666 666 666 666  34  35]


In [120]:
red_copy[4:9]= 0

In [121]:
print red
print red_copy

[ 25  26  27  28 666 666 666 666 666  34  35]
[25 26 27 28  0  0  0  0  0 34 35]


In [134]:
# if u grab a slice and set it to variable without actally using copy, u r just viewing a link to the original array and making
#changes to that slice will change the original array
char= numpy.arange(1,10)

In [135]:
char

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
char=char.reshape(3,3)

In [144]:
char

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
char[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
char[0:2,0:2] #submatrices

array([[1, 2],
       [4, 5]])

In [150]:
#double bracket format and single bracket format
char
char[0][0]# doublebracket
char[0] # single bracket
char[0,0] # single bracket less prone to error

array([1, 2, 3])

In [153]:
char[0:1]

array([[1, 2, 3]])

In [154]:
char

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [155]:
char[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [156]:
char[1:,0:]

array([[4, 5, 6],
       [7, 8, 9]])

In [157]:
#conditional selection , very important
tick= numpy.arange(1,11)

In [158]:
tick

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [159]:
tick1 = tick >5 # using a comparator opertor on an array returns  a bool datatype array, use it to index or conditionally select
#elements from that original array where this happened to true

In [160]:
tick1

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [161]:
type(tick1) #use that bool datatype array to index  

numpy.ndarray

In [163]:
tick1.dtype

dtype('bool')

In [165]:
tick[tick1] # getting results only where th boolean array is true

array([ 6,  7,  8,  9, 10])

In [166]:
tick[tick>6]

array([ 7,  8,  9, 10])

# numpy basic operations u can perform
array with array operations
array with scalar operations
universal array functions and more of those


In [167]:
nit= numpy.arange(1,11)

In [168]:
nit

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [169]:
nit*nit

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [170]:
nit*4

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [171]:
nit+nit

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [172]:
nit-nit

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [173]:
nit/nit

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [174]:
nit+1000 #broadcast that element to every element of the array, scalar element wise operation

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010])

In [178]:
nit=nit-1

In [179]:
nit

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [180]:
nit/nit # code continues to run but it gives a warning

C:\Users\pooja\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1])

C:\Users\pooja\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([-1,  0,  1,  0,  0,  0,  0,  0,  0,  0])

In [185]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [186]:
#universal array function
#numpy comes with many, which are essentially mathematical operations used to perform operation and broadcast acros sthe array
numpy.sqrt(nit)

C:\Users\pooja\Anaconda2\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


array([        nan,  0.        ,  1.        ,  1.41421356,  1.73205081,
        2.        ,  2.23606798,  2.44948974,  2.64575131,  2.82842712])

In [187]:
nitt=numpy.arange(2,13)

In [188]:
nitt

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [189]:
numpy.sqrt(nitt)

array([ 1.41421356,  1.73205081,  2.        ,  2.23606798,  2.44948974,
        2.64575131,  2.82842712,  3.        ,  3.16227766,  3.31662479,
        3.46410162])

In [190]:
nitt**2

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [191]:
nitt**nitt

array([         4,         27,        256,       3125,      46656,
           823543,   16777216,  387420489, 1410065408, 1843829075,
       -251658240])

In [192]:
numpy.exp(nitt)

array([  7.38905610e+00,   2.00855369e+01,   5.45981500e+01,
         1.48413159e+02,   4.03428793e+02,   1.09663316e+03,
         2.98095799e+03,   8.10308393e+03,   2.20264658e+04,
         5.98741417e+04,   1.62754791e+05])

In [193]:
nitt.max()

12

In [194]:
nitt.min()

2

In [195]:
numpy.max(nitt)

12

In [197]:
numpy.average(nitt)

7.0

In [198]:
numpy.median(nitt)

7.0

In [200]:
numpy.sin(nitt)


array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,
        0.6569866 ,  0.98935825,  0.41211849, -0.54402111, -0.99999021,
       -0.53657292])

In [201]:
numpy.log(nitt)

array([ 0.69314718,  1.09861229,  1.38629436,  1.60943791,  1.79175947,
        1.94591015,  2.07944154,  2.19722458,  2.30258509,  2.39789527,
        2.48490665])

In [ ]:
link of universal array functions in hoses notebook, numpy array documentaton for universal functions(ufunc)

In [ ]:
# practice universal standard functions acis , stddeiation etc